- name: Install nginx
  apt:
    name: nginx
    state: present
    update_cache: yes

- name: Create nginx cache directory
  file:
    path: /var/cache/nginx/umami
    state: directory
    owner: www-data
    group: www-data
    mode: "0755"

- name: Login to Umami API
  uri:
    url: "http://192.168.0.12:3000/api/auth/login"
    method: POST
    body_format: json
    body:
      username: "{{ umami_username }}"
      password: "{{ umami_password }}"
    headers:
      Content-Type: "application/json"
    return_content: yes
  register: umami_login

- name: Store Umami token
  set_fact:
    umami_token: "{{ umami_login.json.token }}"


- name: Ensure nginx conf.d exists
  file:
    path: /etc/nginx/conf.d
    state: directory

- name: Deploy hardened nginx.conf
  template:
    src: nginx.conf.j2
    dest: /etc/nginx/nginx.conf
  notify: restart nginx

- name: Deploy hardened site config
  template:
    src: portfolio.conf.j2
    dest: /etc/nginx/conf.d/portfolio.conf
  notify: restart nginx

- name: Remove default nginx site
  file:
    path: /etc/nginx/sites-enabled/default
    state: absent

- name: Deploy index.html
  template:
    src: index.html.j2
    dest: /var/www/html/index.html

- name: Deploy visitor counter script
  template:
    src: visitors.js.j2
    dest: /var/www/html/visitors.js

- name: Validate nginx config
  command: nginx -t
  changed_when: false

