- name: Configure nginx
  hosts: nginx
  become: yes
  roles:
    - web

# - name: Configure cloudflared
#   hosts: cloudflared
#   become: yes
#   roles:
#     - cloudflared

# - name: Configure umami
#   hosts: umami
#   become: yes
#   roles:
#     - umami
