name: Configure Containers with Ansible

on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Terraform Proxmox Deploy"]
    types:
      - completed

jobs:
  ansible:
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      - name: Download inventory artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: ansible-inventory
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          path: infra/ansible/inventory

      - name: Run Ansible Playbook
        run: |
          ansible-playbook -i ansible/inventory/generated.yml ansible/deploy.yml \
          --extra-vars "cloudflared_tunnel_token=${{ secrets.CLOUDFLARED_TUNNEL_TOKEN }}" \
          --extra-vars "umami_db_password=${{ secrets.UMAMI_DB_PASSWORD }}" \
          --extra-vars "umami_app_secret=${{ secrets.UMAMI_APP_SECRET }}" \
          --extra-vars "umami_username=${{ secrets.UMAMI_USERNAME }}" \
          --extra-vars "umami_password=${{ secrets.UMAMI_PASSWORD }}" \
          --extra-vars "umami_website_id=${{ secrets.WEBSITE_ID }}"