name: Deploy Portfolio

on:
  workflow_dispatch:

  workflow_run:
    workflows: ["Configure Containers with Ansible"]
    types:
      - completed

jobs:
  deploy:
    if: >
      github.event_name == 'workflow_dispatch' ||
      github.event.workflow_run.conclusion == 'success'
    runs-on: self-hosted

    steps:

      #################################################
      # CHECKOUT
      #################################################

      - name: Checkout repo
        uses: actions/checkout@v6.0.2

      #################################################
      # NODE SETUP
      #################################################

      - name: Setup Node
        uses: actions/setup-node@v6.2.0
        with:
          node-version: 20

      #################################################
      # BUILD VITE APP
      #################################################

      - name: Install dependencies
        working-directory: zaki-portfolio-v11
        run: npm ci

      - name: Build portfolio
        working-directory: zaki-portfolio-v11
        run: npm run build

      #################################################
      # DOWNLOAD INVENTORY
      #################################################

      - name: Download inventory artifact
        uses: actions/download-artifact@v7.0.0
        with:
          name: ansible-inventory
          github-token: ${{ github.token }}
          repository: ${{ github.repository }}
          path: ansible/inventory

      #################################################
      # DEPLOY VIA ANSIBLE
      #################################################

      - name: Deploy via Ansible
        run: |
          ansible-playbook \
            -i ansible/inventory/generated.yml \
            ansible-deploy/deploy.yml \
            --extra-vars "vite_build_path=${GITHUB_WORKSPACE}/zaki-portfolio-v11/dist"
