name: Terraform Proxmox Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: infra

    steps:
      #################################################
      # CHECKOUT
      #################################################
      - name: Checkout Repository
        uses: actions/checkout@v4

      #################################################
      # TERRAFORM SETUP
      #################################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3

      #################################################
      # TERRAFORM INIT
      #################################################
      - name: Terraform Init
        run: terraform init

      #################################################
      # TERRAFORM PLAN
      #################################################
      - name: Terraform Plan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ct_password: ${{ secrets.CT_PASSWORD }}
          TF_VAR_ssh_public_key_path: /root/.ssh/proxmox_ansible_key.pub
        run: terraform plan

      #################################################
      # TERRAFORM APPLY
      #################################################
      - name: Terraform Apply
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ct_password: ${{ secrets.CT_PASSWORD }}
          TF_VAR_ssh_public_key_path: /root/.ssh/proxmox_ansible_key.pub
        run: terraform apply -auto-approve
