name: Terraform Proxmox Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: infra

    steps:
      #################################################
      # CHECKOUT
      #################################################
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      #################################################
      # SETUP TERRAFORM
      #################################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      #################################################
      # TERRAFORM INIT
      #################################################
      - name: Terraform Init
        run: terraform init

      #################################################
      # TERRAFORM PLAN
      #################################################
      - name: Terraform Plan
        id: plan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ct_password: ${{ secrets.CT_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}
        run: |
          set +e
          terraform plan -detailed-exitcode -out=tfplan | tee plan_output.txt
          exitcode=$?
          echo "exitcode=$exitcode" >> $GITHUB_OUTPUT
          echo "Terraform plan exit code: $exitcode"
          set -e

          # Exit code meanings:
          # 0 = no changes
          # 2 = changes present
          # 1 = error

          if [ "$exitcode" -eq 1 ]; then
            echo "Terraform plan failed"
            exit 1
          fi
      - name: Show Plan Output (debug)
        run: cat plan_output.txt
      #################################################
      # TERRAFORM APPLY ONLY IF INFRASTRUCTURE CHANGES ARE PRESENT
      #################################################
      - name: Terraform Apply
        if: steps.plan.outputs.exitcode == '2'
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ct_password: ${{ secrets.CT_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve tfplan

      #################################################
      # OUTPUT THE INVENTORY FILE
      #################################################\
      - name: Generate inventory file (no apply)
        run: |
          mkdir -p ansible/inventory

          awk '
          /content.*<<-EOT/ {flag=1;next}
          /^[[:space:]]*EOT/ {flag=0}
          flag
          ' plan_output.txt \
          | sed 's/"//g' \
          | sed 's/^[[:space:]]\{8\}//' \
          > ansible/inventory/generated.yml

      - name: Show inventory (debug)
        run: cat ansible/inventory/generated.yml

      - name: Upload inventory artifact
        uses: actions/upload-artifact@v6.0.0
        with:
          name: ansible-inventory
          path: infra/ansible/inventory/generated.yml
