name: Terraform Proxmox Deploy

on:
  workflow_dispatch:

jobs:
  terraform:
    runs-on: self-hosted

    defaults:
      run:
        working-directory: infra

    steps:
      #################################################
      # CHECKOUT
      #################################################
      - name: Checkout Repository
        uses: actions/checkout@v6.0.2

      #################################################
      # SETUP TERRAFORM
      #################################################
      - name: Setup Terraform
        uses: hashicorp/setup-terraform@v3.1.2

      #################################################
      # TERRAFORM INIT
      #################################################
      - name: Terraform Init
        run: terraform init

      #################################################
      # TERRAFORM PLAN
      #################################################
      - name: Terraform Plan
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ct_password: ${{ secrets.CT_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}
        run: terraform plan

      #################################################
      # TERRAFORM APPLY
      #################################################
      - name: Terraform Apply
        env:
          TF_VAR_pm_api_url: ${{ secrets.PM_API_URL }}
          TF_VAR_pm_api_token_id: ${{ secrets.PM_API_TOKEN_ID }}
          TF_VAR_pm_api_token_secret: ${{ secrets.PM_API_TOKEN_SECRET }}
          TF_VAR_ct_password: ${{ secrets.CT_PASSWORD }}
          TF_VAR_ssh_public_key: ${{ secrets.ANSIBLE_SSH_PUBLIC_KEY }}
        run: terraform apply -auto-approve

      # -------------------------
      # Create Ansible inventory
      # -------------------------
      - name: Generate inventory file
        run: |
          mkdir -p ansible/inventory
          terraform -chdir=terraform output -raw ansible_inventory_yaml > ansible/inventory/generated.yml

      - name: Show inventory (debug)
        run: cat ansible/inventory/generated.yml